### ISSUE TITLE
DS is not defined

### ISSUE THREAD

**Issue by makwanza** [stefanpenner/ember-cli-ember-fire#8]
After following the instructions, getting the following error when visiting the app at http://localhost:4200

<pre><code>
Error while processing route: index DS is not defined ReferenceError: DS is not defined
    at http://localhost:4200/assets/vendor.js:61446:16
    at requireModule (http://localhost:4200/assets/vendor.js:77:29)
    at reify (http://localhost:4200/assets/vendor.js:48:30)
    at requireModule (http://localhost:4200/assets/vendor.js:76:17)
    at resolveOther (http://localhost:4200/assets/vendor.js:61582:20)
    at apply (http://localhost:4200/assets/vendor.js:31592:27)
    at superWrapper (http://localhost:4200/assets/vendor.js:31170:15)
    at __exports__.default.EmberObject.extend.resolve (http://localhost:4200/assets/vendor.js:16687:27)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:16325:25)
    at resolve (http://localhost:4200/assets/vendor.js:14775:32)
</pre></code>

Also:
<pre><code>
 GET http://localhost:4200/assets/ember-data.js.map 404 (Not Found)
</pre></code>

I am new to ember-cli so could be doing something wrong. I appreciate any input.

**Comment by stefanpenner** [comment]
> GET http://localhost:4200/assets/ember-data.js.map 404 (Not Found)

appears un-related

**Comment by stefanpenner** [comment]
ya i can replicate

**Comment by makwanza** [comment]
Great! Thanks for validating!

**Comment by stefanpenner** [comment]
interestingly CI is green, I suspect some dep broke something within its semver drift

**Comment by stefanpenner** [comment]
I just updated everything and stuff works (as best as it ever did) again
https://github.com/stefanpenner/ember-cli-ember-fire/commit/ddd2f152a17dfdd003180815fb510ee09189704b

feel free to report other issues!

**Comment by paulochoi** [comment]
Thank you @stefanpenner
